import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Next.js Learning - RTR",
    template: "",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header
          style={{
            backgroundColor: "rebeccapurple",
            padding: "1rem",
            textAlign: "center",
          }}
        >
          I am header section
        </header>
        <main>{children}</main>

        <footer
          style={{
            backgroundColor: "black",
            color: "white",
            padding: "1rem",
            textAlign: "center",
          }}
        >
          All rights reserved by @Rakib Talukder Rupom
        </footer>
      </body>
    </html>
  );
}
